### ISSUE TITLE
UI/UX改善とデバッグモード実装

### ISSUE THREAD

**Issue by rmc8** [rmc8/gourmet_journey_jp#10]
## 概要
アプリケーションのUI/UX統一性向上とデバッグ機能の実装による開発効率改善。

### デバッグモード機能
- **隠しコマンド**: タイトル5回クリックでデバッグモード切り替え
- **キーボードショートカット**: Ctrl+Shift+D (Windows/Linux) / Cmd+Shift+D (Mac)
- **Firebase接続テスト**: デバッグモード時のみ表示される接続テストボタン
- **視覚的インジケーター**: デバッグモード時のアニメーション付きインジケーター
- **ローカルストレージ**: デバッグモード状態の永続化

### ボタン配色統一化
- **暖色系テーマ**: グルメアプリにふさわしいオレンジベースの配色
- **グラデーション効果**: 微細なグラデーションによる質感向上
- **ホバーエフェクト**: 統一されたインタラクションフィードバック

#### 配色仕様
```css
.btn-primary { background: linear-gradient(135deg, #FFAB40 0%, #FF6F00 100%); }
.btn-secondary-warm { background: linear-gradient(135deg, #FFAB40 0%, #FF8F00 100%); }
.btn-accent { background: linear-gradient(135deg, #FFC107 0%, #FF9800 100%); }
```

### 統計表示改善
- **統一幅**: 都道府県制覇・食事完了・購入済みボックスの幅統一（140px）
- **レスポンシブ対応**: モバイルデバイスでの表示最適化
- **視認性向上**: 適切な余白とフォントサイズ調整

### デバッグモード実装
```typescript
// 状態管理
let debugMode = $state(false);
let titleClickCount = $state(0);

// 隠しコマンド
function handleTitleClick() {
  titleClickCount++;
  if (titleClickCount >= 5) {
    toggleDebugMode();
    titleClickCount = 0;
  }
}
```

### CSS変数活用
```css
:root {
  --primary-color: #FF9800;
  --primary-dark: #F57C00;
  --secondary-color: #FFAB40;
  --secondary-dark: #FF8F00;
}
```

## UX改善効果
- **一貫性**: 全ボタンの統一されたルック&フィール
- **直感性**: グルメアプリに適した温かみのある配色
- **開発効率**: デバッグモードによるFirebase接続テストの簡易化
- **保守性**: CSS変数による配色管理の一元化

## 品質保証
- [x] 各種ボタンの配色統一確認
- [x] デバッグモードの動作確認
- [x] キーボードショートカット動作確認
- [x] レスポンシブデザイン確認
- [x] ローカルストレージ永続化確認

## 影響範囲
- `src/routes/+page.svelte`: メイン実装
- `src/app.css`: グローバルCSS変数定義

この改善により、アプリケーションの統一感が向上し、開発時のデバッグ効率も大幅に改善されました。
