### ISSUE TITLE
星評価UIのホバー効果改善とユーザビリティ向上

### ISSUE THREAD

**Issue by rmc8** [rmc8/gourmet_journey_jp#16]
## 問題の背景
マウスオーバー時に単一の星のみがハイライトされ、選択される星の数が不明確でした。

## 実装した解決策
ホバー時に選択される星以下の全ての星をハイライト表示するよう改善しました。

### 具体的な実装内容
- **状態管理**: `hoveredRating`状態を追加して、ホバー中の星の位置を追跡
- **イベントハンドラー**: `onmouseenter`と`onmouseleave`イベントを各星ボタンに追加
- **視覚的フィードバック**: ホバー時に該当する星以下の全ての星を薄いオレンジ色でハイライト

### CSS変更
```css
.star-button.hovered {
  color: #ffb366; /* 薄いオレンジ色 */
}
```

## 効果
- 一般的な星評価UIの動作パターンに統一
- ユーザビリティの向上（選択される星の数が明確に分かる）
- 直感的な操作感の実現

## 完了状況
✅ 実装完了
✅ 動作確認済み
✅ UI/UX改善効果確認済み
